import { PortfolioProject } from '../models/portfolio-project.model';

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 'oms',
    title: 'Order Management System',
    slug: 'order-management-system',
    category: 'Enterprise Software',
    thumbnail: '',
    challenge: 'The client needed a centralized platform to manage orders across multiple channels, track order status in real-time, and automate processing workflows. The existing system was manual, error-prone, and lacked visibility into order progress.',
    solution: 'We designed and developed a comprehensive Order Management System with role-based access, real-time order tracking, automated workflow processing, and detailed reporting dashboards. The system was built with a scalable architecture to handle growing order volumes.',
    technologies: ['ASP.NET Core', 'Angular', 'SQL Server', 'REST API', 'Entity Framework Core'],
    features: [
      'Real-time order tracking and status updates',
      'Automated workflow processing',
      'Role-based access control',
      'Reporting and analytics dashboard',
      'Multi-channel order integration',
      'Email notifications and alerts',
    ],
    results: [
      'Streamlined order processing workflow',
      'Reduced manual data entry errors',
      'Improved order visibility and tracking',
      'Faster order fulfillment cycle',
    ],
    isDemo: true,
  },
  {
    id: 'crm',
    title: 'CRM System',
    slug: 'crm-system',
    category: 'Business Application',
    thumbnail: '',
    challenge: 'A growing business needed a customer relationship management system to track leads, manage customer interactions, and generate insights through reporting. They required a solution that could integrate with their existing tools and scale with their growth.',
    solution: 'We built a custom CRM system with lead management, customer profiling, interaction tracking, and comprehensive reporting capabilities. The application was designed with a modern Angular frontend and a robust ASP.NET Core backend.',
    technologies: ['ASP.NET Core', 'Angular', 'SQL Server', 'REST API', 'Azure'],
    features: [
      'Lead tracking and management',
      'Customer profile management',
      'Interaction history and notes',
      'Custom reporting and analytics',
      'Task and follow-up management',
      'Data export and import',
    ],
    results: [
      'Centralized customer data management',
      'Improved lead conversion tracking',
      'Better customer relationship insights',
      'Streamlined sales processes',
    ],
    isDemo: true,
  },
  {
    id: 'legacy-mod',
    title: 'Legacy Application Modernization',
    slug: 'legacy-application-modernization',
    category: 'Modernization',
    thumbnail: '',
    challenge: 'A legacy web application built with older .NET Framework technology was becoming increasingly difficult to maintain, had security vulnerabilities, and could not scale to meet growing business demands.',
    solution: 'We performed a comprehensive assessment of the existing application, created a migration plan, and incrementally modernized the application to ASP.NET Core. The new architecture improved performance, security, and maintainability while preserving core business logic.',
    technologies: ['.NET', 'ASP.NET Core', 'Angular', 'SQL Server', 'Docker', 'Azure'],
    features: [
      'Technology upgrade from .NET Framework to .NET Core',
      'Modern responsive UI with Angular',
      'Improved security with modern authentication',
      'Containerized deployment with Docker',
      'Automated CI/CD pipeline',
      'Performance optimization',
    ],
    results: [
      'Improved application performance',
      'Enhanced security posture',
      'Reduced maintenance costs',
      'Scalable and maintainable architecture',
    ],
    isDemo: true,
  },
  {
    id: 'dashboard',
    title: 'Reporting Dashboard',
    slug: 'reporting-dashboard',
    category: 'Analytics',
    thumbnail: '',
    challenge: 'The business needed interactive dashboards to visualize key metrics, generate reports, and gain actionable insights from their data. Existing reporting was manual and time-consuming.',
    solution: 'We developed a comprehensive reporting dashboard with interactive charts, customizable reports, data filtering, and export capabilities. The solution integrated with existing data sources and provided real-time data visualization.',
    technologies: ['Angular', 'TypeScript', 'ASP.NET Core Web API', 'SQL Server', 'Chart.js'],
    features: [
      'Interactive data visualization',
      'Customizable dashboard layouts',
      'Advanced data filtering',
      'Report generation and export',
      'Real-time data updates',
      'Role-based dashboard access',
    ],
    results: [
      'Data-driven decision making',
      'Reduced report generation time',
      'Improved business visibility',
      'Actionable insights from data',
    ],
    isDemo: true,
  },
];
