import { ServiceItem } from '../models/service.model';

export const SERVICES: ServiceItem[] = [
  {
    id: 'custom-software',
    icon: 'devices',
    title: 'Custom Software Development',
    shortDescription: 'Build custom web and enterprise applications based on business requirements.',
    description: 'We design and develop custom software solutions tailored to your unique business needs. From web applications to enterprise systems, we build robust, scalable software that drives efficiency and growth. Our team works closely with you to understand requirements, define architecture, and deliver high-quality applications.',
    features: [
      'Requirements analysis and planning',
      'Custom web application development',
      'Enterprise software solutions',
      'Third-party integrations',
      'Scalable architecture design',
      'Quality assurance and testing',
    ],
    technologies: ['.NET', 'ASP.NET Core', 'Angular', 'SQL Server', 'Azure', 'REST API'],
    slug: 'custom-software-development',
  },
  {
    id: 'dotnet',
    icon: 'code',
    title: '.NET Development',
    shortDescription: 'Robust, scalable and secure applications using ASP.NET Core and C#.',
    description: 'Leverage the power of Microsoft .NET for building enterprise-grade applications. We specialize in ASP.NET Core, Web APIs, MVC applications, and backend services. Our .NET development expertise ensures your applications are performant, secure, and maintainable.',
    features: [
      'ASP.NET Core Web Applications',
      'Web API Development',
      'MVC Architecture',
      'Enterprise Backend Services',
      'Microservices Architecture',
      'Performance Optimization',
    ],
    technologies: ['.NET', 'ASP.NET Core', 'C#', 'Entity Framework Core', 'Web API', 'Azure'],
    slug: 'dotnet-development',
  },
  {
    id: 'angular',
    icon: 'web',
    title: 'Angular Development',
    shortDescription: 'Dynamic and responsive front-end solutions with Angular for modern web applications.',
    description: 'Create modern, responsive, and feature-rich single-page applications with Angular. We build dynamic user interfaces that provide seamless user experiences. Our Angular expertise covers everything from component architecture to state management and performance optimization.',
    features: [
      'Single Page Applications (SPA)',
      'Responsive UI Development',
      'Component-based Architecture',
      'State Management',
      'Progressive Web Apps (PWA)',
      'Performance Optimization',
    ],
    technologies: ['Angular', 'TypeScript', 'RxJS', 'SCSS', 'HTML5', 'Material Design'],
    slug: 'angular-development',
  },
  {
    id: 'api',
    icon: 'api',
    title: 'API Development & Integration',
    shortDescription: 'REST APIs, third-party API integrations and system integrations.',
    description: 'Design, develop, and integrate APIs that connect your systems and enable seamless data flow. We build secure, well-documented REST APIs and handle complex third-party integrations to streamline your business operations.',
    features: [
      'RESTful API Design',
      'Third-party API Integration',
      'API Documentation',
      'Authentication & Authorization',
      'Rate Limiting & Security',
      'API Versioning',
    ],
    technologies: ['ASP.NET Core Web API', 'REST', 'OAuth', 'JWT', 'Swagger', 'Postman'],
    slug: 'api-development',
  },
  {
    id: 'sql',
    icon: 'storage',
    title: 'SQL Server Optimization',
    shortDescription: 'Database design, development, optimization and performance tuning.',
    description: 'Optimize your database performance and design robust data architectures with SQL Server. We specialize in database design, stored procedures, query optimization, and performance tuning to ensure your data layer is fast, reliable, and scalable.',
    features: [
      'Database Design & Architecture',
      'Stored Procedures & Functions',
      'Query Performance Optimization',
      'Index Optimization',
      'Data Migration',
      'Database Monitoring',
    ],
    technologies: ['SQL Server', 'T-SQL', 'Entity Framework Core', 'SSIS', 'Database Design'],
    slug: 'sql-server-optimization',
  },
  {
    id: 'azure',
    icon: 'cloud',
    title: 'Azure & Cloud Solutions',
    shortDescription: 'Deploy, migrate and manage applications using Microsoft Azure cloud services.',
    description: 'Harness the power of Microsoft Azure for cloud deployment, migration, and management. We help businesses move to the cloud, optimize their infrastructure, and leverage Azure services for scalability, reliability, and cost efficiency.',
    features: [
      'Azure App Service Deployment',
      'Cloud Migration',
      'Azure SQL Database',
      'Azure Functions',
      'CI/CD Pipeline Setup',
      'Cloud Architecture Design',
    ],
    technologies: ['Microsoft Azure', 'Azure DevOps', 'Azure SQL', 'Azure Functions', 'Docker'],
    slug: 'azure-cloud-solutions',
  },
  {
    id: 'legacy',
    icon: 'update',
    title: 'Legacy Application Modernization',
    shortDescription: 'Modernize legacy applications to improve performance, security and scalability.',
    description: 'Transform your aging applications into modern, maintainable software. We assess, plan, and execute legacy modernization projects that preserve your business logic while upgrading technology, improving security, and enhancing performance.',
    features: [
      'Legacy Code Assessment',
      'Migration Planning',
      'Technology Upgrade',
      'Data Migration',
      'Incremental Modernization',
      'Risk Mitigation',
    ],
    technologies: ['.NET', 'ASP.NET Core', 'Angular', 'SQL Server', 'Azure', 'Docker'],
    slug: 'legacy-modernization',
  },
  {
    id: 'maintenance',
    icon: 'build',
    title: 'Application Maintenance & Support',
    shortDescription: 'Ongoing support and maintenance to keep your applications running smoothly.',
    description: 'Keep your applications running at peak performance with our comprehensive maintenance and support services. We provide bug fixing, feature enhancements, performance monitoring, security updates, and ongoing technical support.',
    features: [
      'Bug Fixing & Issue Resolution',
      'Feature Enhancements',
      'Performance Monitoring',
      'Security Updates',
      'Technical Support',
      'Code Review & Optimization',
    ],
    technologies: ['.NET', 'Angular', 'SQL Server', 'Azure', 'Git', 'CI/CD'],
    slug: 'maintenance-support',
  },
];

// Services displayed on homepage (first 6)
export const HOME_SERVICES: ServiceItem[] = SERVICES.slice(0, 6);
